// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uniBomberQuote.Shared.Models;

#nullable disable

namespace uniBomberQuote.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250714112257_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("uniBomberQuote.Models.MyText", b =>
                {
                    b.Property<long>("sentenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("MySentences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SentenceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("sentenceId");

                    b.ToTable("DataSentences");
                });
#pragma warning restore 612, 618
        }
    }
}
